[ -z "$PS1" ] && return

export HISTSIZE=10000
export HISTFILESIZE=${HISTSIZE}
export HISTCONTROL=ignoreboth
shopt -s cdspell
shopt -s histappend
shopt -s checkwinsize
shopt -s cmdhist
shopt -s dotglob
shopt -s expand_aliases
shopt -s extglob
shopt -s hostcomplete
shopt -s nocaseglob

set show-all-if-ambiguous on
set show-all-if-unmodified on

alias ls='ls --time-style=+"%d.%m.%Y %H:%M" --color=auto'
alias ll='ls -hl  --time-style=+"%d.%m.%Y %H:%M" --color=auto'
alias la='ls -lah --time-style=+"%d.%m.%Y %H:%M" --color=auto'
alias grep='grep -n'
alias psa='ps -Af | \grep -v grep | \grep'

export LANG=en_US.UTF-8
export QT_QPA_PLATFORMTHEME="qt5ct"

source /data/dune/venv/dune-gdt-python-bindings/bin/activate
cd /data/home/dune-gdt-python-bindings

# we need to account for the fact that a user might be starting this for the first time
# with fresh sources and no CMakeLists.txt.user present (which will break the qtcreator
# config)
[ -e dune-xt/CMakeLists.txt.user ] || cp /data/dune/CMakeLists.txt.user.dune-xt dune/dune-xt/CMakeLists.txt.user
[ -e dune-gdt/CMakeLists.txt.user ] || cp /data/dune/CMakeLists.txt.user.dune-gdt dune/dune-gdt/CMakeLists.txt.user

echo "Welcome to the docker container accompanying"
echo "  https://github.com/ftschindler-work/dune-gdt-python-bindings"
echo "which can be obtained from:"
echo "  https://hub.docker.com/r/ftschindlerwork/dune-gdt-python-bindings"
echo ""
echo "The virtualenv with all prebuilt binaries and Python bindings is already active."
echo "You may start a Jupyter-Notebook server by calling"
echo ""
echo "  ./start_notebook_server.py"
echo ""
echo "and by opening the printed URL starting with 127.0.0.1 in your favorite browser. Alternatively, you can execute"
echo ""
echo "  qtcreator"
echo ""
echo "to start the preconfigured QtCreator IDE to start creating your own Python bindings."

